name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Run tests
        run: npm run test
        env:
          VITE_CLARIFAI_USER_ID: ${{ secrets.VITE_CLARIFAI_USER_ID }}
          VITE_CLARIFAI_PAT:  ${{ secrets.VITE_CLARIFAI_PAT }}
      - name: Build
        run: npm run build
