name: "Test Pull Request"
on:
  pull_request:

jobs:
  test-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: "Install Node"
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "20.11.0"
      - name: "Install Deps"
        run: npm ci
      - name: "Lint"
        run: npm run lint
      - name: "Test"
        run: npx vitest --coverage.enabled true unit.test
      - name: Prepare Branch Name
        run: |
          echo "CLEAN_BRANCH=$(echo '${{ github.head_ref }}' | sed 's/[":<>|*?\r\n\\\/]/-/g')" >> $GITHUB_ENV
      - name: "Upload Coverage"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: coverage-${{ env.CLEAN_BRANCH }}
          path: coverage

  test-main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          ref: main
      - name: "Install Node"
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "20.11.0"
      - name: "Install Deps"
        run: npm ci
      - name: "Test"
        run: npx vitest --coverage.enabled true unit.test
      - name: "Upload Coverage"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: coverage-main
          path: coverage

  report-coverage:
    needs: [test-pr, test-main]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      pull-requests: write
    steps:
      - name: Prepare Branch Name
        run: |
          echo "CLEAN_BRANCH=$(echo '${{ github.head_ref }}' | sed 's/[":<>|*?\r\n\\\/]/-/g')" >> $GITHUB_ENV
      - name: "Download Coverage Artifacts"
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: coverage-${{ env.CLEAN_BRANCH }}
          path: coverage
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: coverage-main
          path: coverage-main
      - name: "Report Coverage"
        uses: davelosert/vitest-coverage-report-action@3c50566c523e04813df28de8f7c48dd97d663f1c # v2
        with:
          json-summary-compare-path: coverage-main/coverage-summary.json
